#!/bin/zsh
#参数:
#1. 重复次数
#2. 最少连接数
#3. 连接数增加数
#4. 单次时间

#创建一个文件，存储测试结果
#各列分别为连接数，吞吐量，丢包率

f='autotest_result.txt'
touch $f 
cat /dev/null>$f
#重复进行ns2测试，重复次数为本脚本第一个参数
repeat_times=$1

#要传给tcl脚本的参数为：TCP连接数 $2+$3 共 $1个不同的连接数量，如$1=3,$2=20,$3=10,那么要测试的连接数就是20,30,40
con_num_init=$2
con_num_inc=$3
con_num_max=$2+($1-1)*$3
single_test_time=$4

for ((i=$con_num_init;i<=$con_num_max;))        #注意是双小括号，由于受其他语言的影响，很容易搞错  
do  
 ns single_test.tcl $i $single_test_time  # 执行测试
 echo 连接数为$i 
 #awk -f link.awk out.tr # 得到吞吐量
 #第一列
 echo -n $i >> $f # -n表示不换行，>>表示追加
 echo -n '\t' >> $f
 #第二列
 awk -f awks/measure-goodput.awk out.tr >> $f # 得到吞吐量
 echo -n '\t' >> $f
 #第三列
 awk -f awks/measure-loss-rate.awk out.tr >> $f # 得到loss-rate
 echo -n '\t' >> $f
 #第三列
 awk -f awks/measure-delay-link.awk out.tr >> $f # 得到loss-rate
 echo -n '\t' >> $f
 i=$i+$con_num_inc
 echo -n '\n' >> $f
done 


