#!/bin/zsh
#参数:
#1. 连接数
#2. 时间
#3. 最后需要多少份数据

#创建一个文件，存储测试结果
#各列分别为连接数，吞吐量，丢包率

f='autotest_result.txt'
touch $f 
cat /dev/null>$f

#要传给tcl脚本的参数为：TCP连接数 $2+$3 共 $1个不同的连接数量，如$1=3,$2=20,$3=10,那么要测试的连接数就是20,30,40
con_num=$1
total_time=$2
data_num=$3

let interval=$2/$3

ns single_test.tcl $con_num $total_time  # 执行测试
echo 连接数为$con_num 

i=0
while [ "$i" -lt "$data_num" ]
do  
 #awk -f link.awk out.tr # 得到吞吐量
 #第一列
 #echo -n $i >> $f # -n表示不换行，>>表示追加
 #echo -n '\t' >> $f
 #第二列
 awk -f awks/measure-goodput.awk out.tr >> $f # 得到吞吐量
 echo -n '\t' >> $f
 #第三列
 awk -f awks/measure-loss-rate.awk out.tr >> $f # 得到loss-rate
 echo -n '\t' >> $f
 #第四列
 #awk -f awks/measure-delay-link.awk out.tr >> $f # 得到delay-link
 #echo -n '\t' >> $f
 #第五列
 #awk -f awks/measure-jitter.awk out.tr >> $f # 得到jitter
 #echo -n '\t' >> $f
 let i=$i+1
 echo -n '\n' >> $f
 #sleep $interval
done 
